name: Deploy Serverless User Registration

on:
  push:
    branches:
      - main
      - sprint3

env:
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build Quarkus Uber Jar
        run: |
          rm -rf ./build/
          chmod +x ./gradlew
          ./gradlew clean build
          ls -la ./build/

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Inicializar Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Validar Terraform
        run: terraform validate
        working-directory: ./terraform

      - name: Aplicar Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform
